### ISSUE TITLE
Running pong from shared cluster HPCC

### ISSUE THREAD

**Issue by vinod1981** [ramachandran-lab/pong#26]
I am running pong from HPCC cluster and as already mentioned, I tried one option especially mentioned #16 but getting this error.
/homes/vkumar/.local/bin/pong -m qmatix_pong -i popfile_chr7_mod.txt -n poporder_chr7_mod.txt

```
Parsing input and generating cluster network graph
Matching clusters within each K and finding representative runs
For K=1, there is 1 mode across 1 run.
For K=2, there is 1 mode across 1 run.
For K=3, there is 1 mode across 1 run.
For K=4, there is 1 mode across 1 run.
For K=5, there is 1 mode across 1 run.
For K=6, there is 1 mode across 1 run.
For K=7, there is 1 mode across 1 run.
For K=8, there is 1 mode across 1 run.
For K=9, there is 1 mode across 1 run.
For K=10, there is 1 mode across 1 run.
Matching clusters across K
Finding best alignment for all runs within and across K
match time: 0.56s
align time: 0.04s
total time: 0.69s
Traceback (most recent call last):
  File "/homes/vkumar/.local/bin/pong", line 8, in <module>
    sys.exit(main())
  File "/homes/vkumar/.local/lib/python3.8/site-packages/pong/main.py", line 301, in main
    app.listen(opts.port)
  File "/homes/vkumar/.local/lib/python3.8/site-packages/tornado/web.py", line 2109, in listen
    server.listen(port, address)
  File "/homes/vkumar/.local/lib/python3.8/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/homes/vkumar/.local/lib/python3.8/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use

```

Thanks,
Vinod

**Comment by abehr** [comment]
Hi Vinod, it looks like the default port pong uses is already in use. Can you try specifying a different one with the `--port` flag and let me know if that works?

**Comment by vinod1981** [comment]
Dear Abehr,
It is working now, actually I wasn't using name of remote host on my local computer properly.
Now it is working.
Thanks,
